name: Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  #  Create service containers
  test:
    name: Test
    runs-on: ubuntu-latest

    container:
      image: node:10.16-jessie

    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Create env variables
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: password
          POSTGRES_DB: chat
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      # Get copy of code in the repository before running tests
      - name: Checkout repository code
        uses: actions/checkout@v2

      - run: |
          apt-get update
          apt-get install --yes --no-install-recommends postgresql-client

      # Create tables described in init.sql
      - name: Create tables from init.sql
        run: |
          PGPASSWORD=password psql -h postgres -U postgres -tc "CREATE TABLE public.users (
                id SERIAL,
                username VARCHAR(50) NOT NULL,
                password VARCHAR(50) NOT NULL,
                CONSTRAINT user_pkey PRIMARY KEY (id)
            );"

      - name: Create env file
        run: |
          touch .env
          echo DB_USERNAME: "postgres" >> .env
          echo DB_PASSWORD: "password" >> .env
          echo DB_NAME: "golang-server" >> .env
          echo DB_HOST: "postgres" >> .env

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./cmd/...
